Fixed Dagger model error: missing directory path
- The issue was not with the player submodels, but with the shop_skins_submodels.sma file, where the Daggers are defined.
-The error occurred due to a missing directory path in the g_Daggers array.
- This commit fixes the issue related to the model precache error:
Host_Error: PF_precache_model_I_internal: Bad string '' FATAL ERROR (shutting down): Host_Error: PF_precache_model_I_internal: Bad string ''.
- The problem has now been resolved.